# Generated by Django 6.0.4 on 2026-05-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
