# Generated by Django 6.0.4 on 2026-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailotp_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
